/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: deslancer (https://sketchfab.com/deslancer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/abstract-core-9f8584b1917d47f2ad14d65469b48f44
Title: Abstract Core
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/abstract_core.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 3.5]}>
          <group
            name="5a1760bdd50c4d0b9de53146583a1de9fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="CINEMA_4D_Editor"
                  position={[266.975, -28.315, -224.776]}
                  rotation={[-Math.PI, -0.766, -3.078]}
                >
                  <group name="Object_5" />
                </group>
                <group name="Backup">
                  <group name="Boole" />
                  <group name="Boole_1" />
                  <group name="Boole_2" />
                </group>
                <group name="Cloner">
                  <group name="Big_0">
                    <mesh
                      name="Big_0_Base_0"
                      geometry={nodes.Big_0_Base_0.geometry}
                      material={materials.Base}
                    />
                  </group>
                  <group
                    name="Big_1"
                    rotation={[-0.014, 0.018, 0.21]}
                    scale={0.979}
                  >
                    <mesh
                      name="Big_1_Base_0"
                      geometry={nodes.Big_1_Base_0.geometry}
                      material={materials.Base}
                    />
                  </group>
                  <group
                    name="Big_2"
                    rotation={[-0.029, 0.036, 0.42]}
                    scale={0.958}
                  >
                    <mesh
                      name="Big_2_Base_0"
                      geometry={nodes.Big_2_Base_0.geometry}
                      material={materials.Base}
                    />
                  </group>
                  <group
                    name="Big_3"
                    rotation={[-0.044, 0.054, 0.63]}
                    scale={0.938}
                  >
                    <mesh
                      name="Big_3_Base_0"
                      geometry={nodes.Big_3_Base_0.geometry}
                      material={materials.Base}
                    />
                  </group>
                  <group
                    name="Big_4"
                    rotation={[-0.059, 0.071, 0.84]}
                    scale={0.917}
                  >
                    <mesh
                      name="Big_4_Base_0"
                      geometry={nodes.Big_4_Base_0.geometry}
                      material={materials.Base}
                    />
                  </group>
                  <group
                    name="Big_5"
                    rotation={[-0.075, 0.089, 1.051]}
                    scale={0.896}
                  >
                    <mesh
                      name="Big_5_Base_0"
                      geometry={nodes.Big_5_Base_0.geometry}
                      material={materials.Base}
                    />
                  </group>
                  <group
                    name="Big_6"
                    rotation={[-0.09, 0.106, 1.262]}
                    scale={0.875}
                  >
                    <mesh
                      name="Big_6_Base_0"
                      geometry={nodes.Big_6_Base_0.geometry}
                      material={materials.Base}
                    />
                  </group>
                  <group
                    name="Big_7"
                    rotation={[-0.106, 0.122, 1.473]}
                    scale={0.854}
                  >
                    <mesh
                      name="Big_7_Base_0"
                      geometry={nodes.Big_7_Base_0.geometry}
                      material={materials.Base}
                    />
                  </group>
                  <group
                    name="Big_8"
                    rotation={[-0.122, 0.139, 1.685]}
                    scale={0.833}
                  >
                    <mesh
                      name="Big_8_Base_0"
                      geometry={nodes.Big_8_Base_0.geometry}
                      material={materials.Base}
                    />
                  </group>
                  <group
                    name="Big_9"
                    rotation={[-0.139, 0.155, 1.897]}
                    scale={0.813}
                  >
                    <mesh
                      name="Big_9_Base_0"
                      geometry={nodes.Big_9_Base_0.geometry}
                      material={materials.Base}
                    />
                  </group>
                  <group
                    name="Big_10"
                    rotation={[-0.156, 0.171, 2.109]}
                    scale={0.792}
                  >
                    <mesh
                      name="Big_10_Base_0"
                      geometry={nodes.Big_10_Base_0.geometry}
                      material={materials.Base}
                    />
                  </group>
                  <group
                    name="Big_11"
                    rotation={[-0.173, 0.187, 2.322]}
                    scale={0.771}
                  >
                    <mesh
                      name="Big_11_Base_0"
                      geometry={nodes.Big_11_Base_0.geometry}
                      material={materials.Base}
                    />
                  </group>
                  <group
                    name="Small_12"
                    rotation={[-0.191, 0.203, 2.534]}
                    scale={0.75}
                  >
                    <mesh
                      name="Small_12_Base_0"
                      geometry={nodes.Small_12_Base_0.geometry}
                      material={materials.Base}
                    />
                  </group>
                  <group
                    name="Small_13"
                    rotation={[-0.208, 0.218, 2.748]}
                    scale={0.729}
                  >
                    <mesh
                      name="Small_13_Base_0"
                      geometry={nodes.Small_13_Base_0.geometry}
                      material={materials.Base}
                    />
                  </group>
                  <group
                    name="Small_14"
                    rotation={[-0.227, 0.233, 2.961]}
                    scale={0.708}
                  >
                    <mesh
                      name="Small_14_Base_0"
                      geometry={nodes.Small_14_Base_0.geometry}
                      material={materials.Base}
                    />
                  </group>
                  <group
                    name="Small_15"
                    rotation={[-0.245, 0.247, -3.108]}
                    scale={0.688}
                  >
                    <mesh
                      name="Small_15_Base_0"
                      geometry={nodes.Small_15_Base_0.geometry}
                      material={materials.Base}
                    />
                  </group>
                  <group
                    name="Small_16"
                    rotation={[-0.264, 0.262, -2.894]}
                    scale={0.667}
                  >
                    <mesh
                      name="Small_16_Base_0"
                      geometry={nodes.Small_16_Base_0.geometry}
                      material={materials.Base}
                    />
                  </group>
                  <group
                    name="Small_17"
                    rotation={[-0.283, 0.276, -2.679]}
                    scale={0.646}
                  >
                    <mesh
                      name="Small_17_Base_0"
                      geometry={nodes.Small_17_Base_0.geometry}
                      material={materials.Base}
                    />
                  </group>
                  <group
                    name="Small_18"
                    rotation={[-0.302, 0.289, -2.464]}
                    scale={0.625}
                  >
                    <mesh
                      name="Small_18_Base_0"
                      geometry={nodes.Small_18_Base_0.geometry}
                      material={materials.Base}
                    />
                  </group>
                  <group
                    name="Small_19"
                    rotation={[-0.322, 0.303, -2.249]}
                    scale={0.604}
                  >
                    <mesh
                      name="Small_19_Base_0"
                      geometry={nodes.Small_19_Base_0.geometry}
                      material={materials.Base}
                    />
                  </group>
                  <group
                    name="Small_20"
                    rotation={[-0.342, 0.316, -2.033]}
                    scale={0.583}
                  >
                    <mesh
                      name="Small_20_Base_0"
                      geometry={nodes.Small_20_Base_0.geometry}
                      material={materials.Base}
                    />
                  </group>
                  <group
                    name="Small_21"
                    rotation={[-0.363, 0.328, -1.818]}
                    scale={0.563}
                  >
                    <mesh
                      name="Small_21_Base_0"
                      geometry={nodes.Small_21_Base_0.geometry}
                      material={materials.Base}
                    />
                  </group>
                  <group
                    name="Small_22"
                    rotation={[-0.384, 0.34, -1.601]}
                    scale={0.542}
                  >
                    <mesh
                      name="Small_22_Base_0"
                      geometry={nodes.Small_22_Base_0.geometry}
                      material={materials.Base}
                    />
                  </group>
                  <group
                    name="Small_23"
                    rotation={[-0.405, 0.352, -1.384]}
                    scale={0.521}
                  >
                    <mesh
                      name="Small_23_Base_0"
                      geometry={nodes.Small_23_Base_0.geometry}
                      material={materials.Base}
                    />
                  </group>
                  <group
                    name="Small_24"
                    rotation={[-0.426, 0.363, -1.167]}
                    scale={0.5}
                  >
                    <mesh
                      name="Small_24_Base_0"
                      geometry={nodes.Small_24_Base_0.geometry}
                      material={materials.Base}
                    />
                  </group>
                </group>
                <group name="Sphere" position={[-1.616, -2.444, 0.779]}>
                  <mesh
                    name="Sphere_Core_0"
                    geometry={nodes.Sphere_Core_0.geometry}
                    material={materials.Core}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/abstract_core.glb");
